# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt
''' 2 layers neural network to reconstruct a deterministic signal y
generated by truncation of the abs of the fft of an input x  '''

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10


#t = np.random.randn(D_in)
t = np.linspace(-1,1,D_in)
f = np.linspace(0,5,N)

x = np.zeros([N, D_in])

l=enumerate(f)



for indx,val in enumerate(f):
    freq=f[indx]
    #print(freq)
    x[indx,:] = np.sin(2*np.pi*freq*t)

# Create random input and output data
x = x #+ np.random.randn(N, D_in)
_y = np.abs((np.fft.fft((x))))

y = _y[:,0:D_out]
#y= y/np.amax(y) 


#y = np.random.randn(N, D_out)
#y= y/np.amax(y) 
#print(y.shape)

f_index = 30

plt.plot(x[:][f_index])
plt.title('x at frequency: '+ str(f[f_index]))
plt.show()


plt.plot(y[:][f_index])
plt.title('y (fft of x) at frequency: '+ str(f[f_index]))
plt.show()

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    

plt.title('reconstructed y at frequency: '+ str(f[f_index]))
plt.plot(y_pred[f_index])
plt.show()